name: Deployment CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download repository.
      uses: actions/checkout@v2
      
    - name: Install & Setup Node.js.
      uses: actions/setup-node@v1
      
    - name: Put private key in file.
      run: echo $PRIVATE_KEY >> id_rsa
      env:
        PRIVATE_KEY: ${{secrets.PROD_PRIVATE_KEY}}

    - name: Fix permissions on key file.
      run: chmod 700 id_rsa
    
    - run: cat id_rsa
    - run: ls
      
    - name: Install PM2.
      run: npm -g i pm2
      
    - name: Deploy via PM2.
      run: pm2 deploy ecosystem.config.js production --force
      env:
        PROD_USER: ${{secrets.PROD_USER}}
        PROD_HOST: ${{secrets.PROD_HOST}}
        PROD_PATH: ${{secrets.PROD_PATH}}
