name: Deployment CI
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: echo $PRIVATE_KEY >> id_rsa
      env:
        PRIVATE_KEY: ${{secrets.PROD_PRIVATE_KEY}}
    - run: npm ci
    - run: pm2 deploy ecosystem.config.js production --force
      env:
        PROD_USER: ${{secrets.PROD_USER}}
        PROD_HOST: ${{secrets.PROD_HOST}}
        PROD_PATH: ${{secrets.PROD_PATH}}
